
name: "Static Analysis"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/static-analysis.yml"
      - "composer.*"
      - "lib/**"
      - "phpstan*"
      - "tests/**"
  push:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/static-analysis.yml"
      - "composer.*"
      - "lib/**"
      - "phpstan*"
      - "tests/**"

jobs:
  static-analysis-phpstan:
    name: "Static Analysis with PHPStan"
    runs-on: "ubuntu-20.04"

    strategy:
      matrix:
        php-version:
          - "7.4"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v2"

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"

      - name: "Cache dependencies installed with composer"
        uses: "actions/cache@v2"
        with:
          path: "~/.composer/cache"
          key: "php-${{ matrix.php-version }}-composer-locked-${{ hashFiles('composer.lock') }}"
          restore-keys: "php-${{ matrix.php-version }}-composer-locked-"

      - name: "Install dependencies with composer"
        run: "composer install --no-interaction --no-progress --no-suggest"

      - name: "Run a static analysis with phpstan/phpstan"
        run: "vendor/bin/phpstan analyse"
